include: package:flutter_lints/flutter.yaml

linter:
  rules:
    public_member_api_docs: false
    lines_longer_than_80_chars: false

    avoid_print: true
    require_trailing_commas: true
    always_put_required_named_parameters_first: false
    no_default_cases: false

formatter:
  page_width: 100
  trailing_commas: preserve